---
- name: update tex
  hosts: all
  become: true

  tasks:

    - name: Update tex
      community.docker.docker_container_exec:
        container: overleaf
        command: /bin/bash -c "cd /root ; rm -rf install-tl-* ;  curl -L -o tl-unx.tar.gz https://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz ; tar -xzf tl-unx.tar.gz; cd install-tl-*; perl ./install-tl --no-interaction "



