services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    volumes:
      - "/root/nginx/key.pem:/certs/nginx_key.pem:ro"
      - "/root/nginx/ca.pem:/certs/nginx_certificate.pem:ro"
      - "/root/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - "0.0.0.0:443:443"
      - "0.0.0.0:80:80"
    environment:
      NGINX_WORKER_PROCESSES: "4"
      NGINX_WORKER_CONNECTIONS: "768"
    network_mode: bridge
