# docker network create overleaf-network
services:
  overleafserver:
    image: "sharelatex/sharelatex:5.1.1"
    container_name: overleafserver
    hostname: overleafserver
    restart: always
    volumes:
      - overleaf_data:/var/lib/overleaf
      - /var/run/docker.sock:/var/run/docker.sock
# Track Changes
      - /root/overleafserver/track/web/app/src/Features/Project/ProjectEditorHandler.js:/overleaf/services/web/app/src/Features/Project/ProjectEditorHandler.js
      - /root/overleafserver/track/web/modules/track-changes/app/src/TrackChangesController.js:/overleaf/services/web/modules/track-changes/app/src/TrackChangesController.js
      - /root/overleafserver/track/web/modules/track-changes/app/src/TrackChangesRouter.js:/overleaf/services/web/modules/track-changes/app/src/TrackChangesRouter.js
      - /root/overleafserver/track/web/modules/track-changes/index.js:/overleaf/services/web/modules/track-changes/index.js
# Fix latex shell escape
      - /root/overleafserver/escape/LatexRunner.js:/overleaf/services/clsi/app/js/LatexRunner.js
# Add ldap
      - /root/overleafserver/ldap/app/src/AuthenticationControllerLdap.js:/overleaf/services/web/modules/ldap-authentication/app/src/AuthenticationControllerLdap.js
      - /root/overleafserver/ldap/app/src/AuthenticationManagerLdap.js:/overleaf/services/web/modules/ldap-authentication/app/src/AuthenticationManagerLdap.js
      - /root/overleafserver/ldap/app/src/InitLdapAuthentication.js:/overleaf/services/web/modules/ldap-authentication/app/src/InitLdapAuthentication.js
      - /root/overleafserver/ldap/app/src/LdapContacts.js:/overleaf/services/web/modules/ldap-authentication/app/src/LdapContacts.js
      - /root/overleafserver/ldap/app/src/LdapStrategy.js:/overleaf/services/web/modules/ldap-authentication/app/src/LdapStrategy.js
      - /root/overleafserver/ldap/index.js:/overleaf/services/web/modules/ldap-authentication/index.js
      - /root/overleafserver/ldap/app/src/Features/Authentication/AuthenticationController.js:/overleaf/services/web/app/src/Features/Authentication/AuthenticationController.js 
      - /root/overleafserver/ldap/app/src/Features/PasswordReset/PasswordResetController.js:/overleaf/services/web/app/src/Features/PasswordReset/PasswordResetController.js
      - /root/overleafserver/ldap/app/src/Features/PasswordReset/PasswordResetHandler.js:/overleaf/services/web/app/src/Features/PasswordReset/PasswordResetHandler.js
      - /root/overleafserver/ldap/app/src/Features/User/UserController.js:/overleaf/services/web/app/src/Features/User/UserController.js
      - /root/overleafserver/ldap/app/src/infrastructure/Features.js:/overleaf/services/web/app/src/infrastructure/Features.js
      - /root/overleafserver/ldap/app/views/user/login.pug:/overleaf/services/web/app/views/user/login.pug
      - /root/overleafserver/ldap/web/config/settings.defaults.js:/overleaf/services/web/config/settings.defaults.js
      - /root/overleafserver/ldap/frontend/js/features/ide-react/context/review-panel/hooks/use-review-panel-state.ts:/overleaf/services/web/frontend/js/features/ide-react/context/review-panel/hooks/use-review-panel-state.ts
      - /root/overleafserver/ldap/frontend/js/features/source-editor/hooks/use-codemirror-scope.ts:/overleaf/services/web/frontend/js/features/source-editor/hooks/use-codemirror-scope.ts
      - /root/overleafserver/ldap/locales/en.json:/overleaf/services/web/locales/en.json
      - /root/overleafserver/ldap/modules/launchpad/app/src/LaunchpadController.js:/overleaf/services/web/modules/launchpad/app/src/LaunchpadController.js
      - /root/overleafserver/ldap/modules/launchpad/app/views/launchpad.pug:/overleaf/services/web/modules/launchpad/app/views/launchpad.pug
      - /root/overleafserver/ldap/patches/ldapauth-fork+4.3.3.patch:/overleaf/patches/ldapauth-fork+4.3.3.patch

# Will use the ldap version with tracking
#      - /root/overleafserver/track/web/config/settings.defaults.js:/overleaf/services/web/config/settings.defaults.js
      - /root/overleafserver/ldap/app/views/user/settings.pug:/overleaf/services/web/app/views/user/settings.pug


    ports:
      - 11001:80
    environment:
      GIT_BRIDGE_ENABLED: "false"
      GIT_BRIDGE_HOST: "git-bridge"
      GIT_BRIDGE_PORT: "8000"

      REDIS_HOST: "overleafredis"
      REDIS_PORT: "6379"
      OVERLEAF_REDIS_HOST: "overleafredis"

      V1_HISTORY_URL: "http://127.0.0.1:3100/api"
      OVERLEAF_MONGO_URL: "mongodb://overleafmongo/sharelatex"
      OVERLEAF_APP_NAME: "FB1 University of Bremen Overleaf"
      ENABLED_LINKED_FILE_TYPES: "project_file,project_output_file"
      ENABLE_CONVERSIONS: "true"
      EMAIL_CONFIRMATION_DISABLED: "false"
      OVERLEAF_BEHIND_PROXY: "true"
      OVERLEAF_SECURE_COOKIE: "true"
      OVERLEAF_SITE_URL: "https://overlead.neuro.uni-bremen.de"
      OVERLEAF_NAV_TITLE: "FB1 Overleaf"
      OVERLEAF_ADMIN_EMAIL: "overleaf@uni-bremen.de"
      
      OVERLEAF_EMAIL_FROM_ADDRESS: "overleaf@uni-bremen.de"
      OVERLEAF_EMAIL_SMTP_HOST: "smtp.uni-bremen.de"
      OVERLEAF_EMAIL_SMTP_PORT: "465"
      OVERLEAF_EMAIL_SMTP_SECURE: "true"
      OVERLEAF_EMAIL_SMTP_USER: "overleaf"
      OVERLEAF_EMAIL_SMTP_PASS: ${EMAIL_PASS}
      OVERLEAF_EMAIL_SMTP_LOGGER: "true"
      OVERLEAF_CUSTOM_EMAIL_FOOTER: "This system is run by the ITP"
      # OVERLEAF_EMAIL_SMTP_IGNORE_TLS: "true"
      # OVERLEAF_EMAIL_SMTP_TLS_REJECT_UNAUTH: "false"
      
      DOCKER_RUNNER: 'true'
      TEXLIVE_IMAGE_USER: 'www-data'
      COMPILES_HOST_DIR: "/var/lib/docker/volumes/overleafserver_overleaf_data/_data/data/compiles"
      SANDBOXED_COMPILES: 'true'
      SANDBOXED_COMPILES_SIBLING_CONTAINERS: 'true'
      SANDBOXED_COMPILES_HOST_DIR: "/var/lib/docker/volumes/overleafserver_overleaf_data/_data/data/compiles"
      TEXLIVE_IMAGE: texlive/texlive:latest-full
      SYNCTEX_BIN_HOST_PATH: "/var/lib/docker/volumes/overleafserver_overleaf_data/_data/bin/synctex"

    networks:
      - overleaf-network

volumes:
  overleaf_data:


networks:
  overleaf-network:
    external: true

