# docker network create overleaf-network
services:
  overleafserver:
    image: "sharelatex/sharelatex:5.0.7"
    container_name: overleafserver
    hostname: overleafserver
    restart: always
    volumes:
      - overleaf_data:/var/lib/overleaf
      - overleaf_tex2024:/usr/local/texlive/2024
      - overleaf_tex2024:/usr/local/texlive/2023
      - /var/run/docker.sock:/var/run/docker.sock
# Fix Email
      - /root/overleafserver/UserRegistrationHandler.js:/overleaf/services/web/app/src/Features/User/UserRegistrationHandler.js
# Fix Email Admin Address
      - /root/overleafserver/EmailBuilder.js:/overleaf/services/web/app/src/Features/Email/EmailBuilder.js
# Track Changes
      - /root/overleafserver/services/web/app/src/Features/Project/ProjectEditorHandler.js:/overleaf/services/web/app/src/Features/Project/ProjectEditorHandler.js
      - /root/overleafserver/services/web/modules/track-changes/app/src/TrackChangesController.js:/overleaf/services/web/modules/track-changes/app/src/TrackChangesController.js
      - /root/overleafserver/services/web/modules/track-changes/app/src/TrackChangesRouter.js:/overleaf/services/web/modules/track-changes/app/src/TrackChangesRouter.js
      - /root/overleafserver/services/web/modules/track-changes/index.js:/overleaf/services/web/modules/track-changes/index.js
      - /root/overleafserver/services/web/config/settings.defaults.js:/overleaf/services/web/config/settings.defaults.js
      - /root/overleafserver/services/web/app/src/Features/Chat/ChatManager.js:/overleaf/services/web/app/src/Features/Chat/ChatManager.js
      - /root/overleafserver/services/web/app/src/Features/DocumentUpdater/DocumentUpdaterHandler.js:/overleaf/services/web/app/src/Features/DocumentUpdater/DocumentUpdaterHandler.js

    ports:
      - 11001:80
    environment:
      GIT_BRIDGE_ENABLED: "false"
      GIT_BRIDGE_HOST: "git-bridge"
      GIT_BRIDGE_PORT: "8000"

      REDIS_HOST: "overleafredis"
      REDIS_PORT: "6379"
      OVERLEAF_REDIS_HOST: "overleafredis"

      V1_HISTORY_URL: "http://127.0.0.1:3100/api"
      OVERLEAF_MONGO_URL: "mongodb://overleafmongo/sharelatex"
      OVERLEAF_APP_NAME: "FB1 University of Bremen Overleaf"
      ENABLED_LINKED_FILE_TYPES: "project_file,project_output_file"
      ENABLE_CONVERSIONS: "true"
      EMAIL_CONFIRMATION_DISABLED: "false"
      OVERLEAF_BEHIND_PROXY: "true"
      OVERLEAF_SECURE_COOKIE: "true"
      OVERLEAF_SITE_URL: "https://overlead.neuro.uni-bremen.de"
      OVERLEAF_NAV_TITLE: "FB1 Overleaf"
      OVERLEAF_ADMIN_EMAIL: "overleaf@uni-bremen.de"
      
      OVERLEAF_EMAIL_FROM_ADDRESS: "overleaf@uni-bremen.de"
      OVERLEAF_EMAIL_SMTP_HOST: "smtp.uni-bremen.de"
      OVERLEAF_EMAIL_SMTP_PORT: "465"
      OVERLEAF_EMAIL_SMTP_SECURE: "true"
      OVERLEAF_EMAIL_SMTP_USER: "overleaf"
      OVERLEAF_EMAIL_SMTP_PASS: ${EMAIL_PASS}
      OVERLEAF_EMAIL_SMTP_LOGGER: "true"
      OVERLEAF_CUSTOM_EMAIL_FOOTER: "This system is run by the ITP"
      # OVERLEAF_EMAIL_SMTP_IGNORE_TLS: "true"
      # OVERLEAF_EMAIL_SMTP_TLS_REJECT_UNAUTH: "false"

    networks:
      - overleaf-network

volumes:
  overleaf_data:
  overleaf_tex2024:

networks:
  overleaf-network:
    external: true

