services:
  redis:
    image: "redis:6.2-alpine"
    container_name: "redis"
    hostname: "redis"
    restart: always
    volumes:
      - redis:/data
    ports:
      - 6379:6379
    network_mode: bridge

volumes:
  redis:

