services:
  authentikpostgres:
    image: "postgres:12-alpine"
    container_name: "authentikpostgres"
    hostname: "authentikpostgres"
    restart: always
    shm_size: 128mb
    volumes:
      - authentik_database:/var/lib/postgresql/data
    ports:
      - 6381:5432
    environment:
      POSTGRES_PASSWORD: ${ROOT_PASSWORD}
      POSTGRES_USER: authentik
      POSTGRES_DB: authentik
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U authentik -d authentik'"]
      interval: 10s
      timeout: 3s
      retries: 3

    networks:
      - overleaf-network

volumes:
  authentik_database:


networks:
  overleaf-network:
    external: true

