services:
  authentiknginx:
    image: nginx:stable-alpine
    container_name: authentiknginx
    hostname: authentiknginx
    restart: always
    volumes:
      - "/root/overleafnginx/key.pem:/certs/nginx_key.pem:ro"
      - "/root/overleafnginx/ca.pem:/certs/nginx_certificate.pem:ro"
      - "/root/sso_test_server/authentiknginx/nginx.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - "0.0.0.0:444:444"
      - "0.0.0.0:81:81"
    environment:
      NGINX_WORKER_PROCESSES: "4"
      NGINX_WORKER_CONNECTIONS: "768"
    networks:
      - overleaf-network

networks:
  overleaf-network:
    external: true

