# docker network create overleaf-network
services:
  nodejsdev:
    image: "node:current-alpine"
    container_name: nodejsdev
    hostname: nodejsdev
    restart: always
    command: sleep infinity

    ports:
    - 3000:3000

    volumes:
      - nodejsdev_data:/data
      - "/root/nodejsdev/key.pem:/certs/key.pem:ro"
      - "/root/nodejsdev/ca.pem:/certs/certificate.pem:ro"

    networks:
      - overleaf-network

volumes:
  nodejsdev_data:

networks:
  overleaf-network:
    external: true
